### ISSUE TITLE
How to exclude builtin functions?

### ISSUE THREAD

**Issue by Antonboom** [kisielk/errcheck#208]
Hi!

```yaml
  errcheck:
    exclude-functions:
      - recover
```

```
$ cat example.go
package main

func main() {
	defer func() {
		recover()
	}()
}

$ golangci-lint run example.go
example.go:5:10: Error return value is not checked (errcheck)
		recover()

```
