### ISSUE TITLE
Check blank is broken

### ISSUE THREAD

**Issue by Datadog-MartinG** [kisielk/errcheck#271]
Hello, I am trying testing errcheck linter with golangci-lint, and I am surprised by its behaviour:
```
package main

import (
	"fmt"
	"os"
)

func wrapper() (*os.File, error) {
	return os.Open("does_not_exist.txt")
}

func main() {
	wrapper()         // 1 <- Error return value is not checked (errcheck)
	_, _ = wrapper()  // 2 <- nothing
	f, _ := wrapper() // 3 <- nothing
	fmt.Println("Opened file name:", f.Name())
}
```

With config `.golangci.yml`:
```
linters:
  settings:
    errcheck:
      check-blank: true

  enable:
    - errcheck
```

I would expect that cases 2,3 would return the same error as case 1 as the error is assigned to the blank identifier.

**Comment by Datadog-MartinG** [comment]
Closing as the error is actually with golangci-lint.
The config should be:
```
linters:
  disable-all: true
  enable:
    - errcheck

linters-settings:
  errcheck:
    check-blank: true
```

But their documentation is outdated: https://golangci-lint.run/usage/linters/#errcheck 👎
